INCLUDE = -I/home/jwsv61099/workspace/libraries/libpng-1.6.37/.libs
LIBS = -lpng16

conv1D:
	g++ -g oneDimConv.cpp -o oneDimConv.exe

conv2D:
	g++ -g $(INCLUDE) twoDimConv.cpp $(LIBS) -o twoDimConv.exe